### ISSUE TITLE
Registro do ponto 

### ISSUE THREAD

**Issue by juniorvsm** [pavanad/pontomais#1]
Olá Adilson.
Fiz um teste hoje com o seu script, mas no momento de registrar o ponto ele não mostrou o recibo e lá no aplicativo não mostrou o registro. Acessei o aplicativo e fiz o registro manual e após sincronizar, aí sim apareceu o registro mas com o status "ONLINE", não sincronizou. 

![image](https://user-images.githubusercontent.com/53951593/133493823-14f776f8-d4f2-44b4-beb9-21b5ca85aa5a.png)

**Comment by pavanad** [comment]
Opa !! Tudo bem ?
Quando eu estava desenvolvendo o script a api do pontomais mudou algumas vezes, então pode ser que o response do endpoint que utilizei para registrar foi modificado. A empresa que estou trabalhando parou de utilizar o app do pontomais e não tenho mais acesso ao sistema, mas se quiser me enviar o retorno desse endpoint eu faço a correção aqui ou se preferir corrigir fique a vontade para abrir um pull request.

```python
from pontomais.api.client import PontoMaisClient

pontomais = PontoMaisClient()
pontomais.set_credentials(<username>, <password>)

pontomais.set_location(<address>, <latitude>, <longitude>)
pontomais.authenticate()

register_info = pontomais.register()

print(register_info)
```
